name: Copilot Guidelines

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-guidelines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip

      - name: Run copilot guidelines script
        env:
          # Optionally, the PR runner can populate CHANGED_FILES for better checks
          CHANGED_FILES: ${{ join(fromJson('[]'), ' ') }}
        run: |
          python scripts/check_copilot_guidelines.py --max-loc 300
